language: node_js
sudo: required

node_js:
  - "10"

before_script:
  - pip install --user awscli
  - cd website && npm install --no-save && cd -

script:
  - cd website && npm run build && cd -

branches:
  only:
    - master

deploy:
  provider: script
  script: cd website && aws s3 sync build/partners\ sdk $BUCKET_URI --acl public-read && aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" && cd -
  on:
    branch: master
